### ISSUE TITLE
Error creating Work Item

### ISSUE THREAD

**Issue by maxstefaniv** [MadhukarMoogala/FDA_PlotToPdf_v3#1]
When executed on Task SubmitWorkItemAsync

An error is thrown:
```
Submitting up WorkItem...
Unhandled exception. System.Net.Http.HttpRequestException: The server returned the non-success status code 403 (Forbidden).
More error details:
"User=secretuniwueowner cannot access a resource owned by Owner=AutoCAD.".
```

**Comment by MadhukarMoogala** [comment]
@maxstefaniv  - sorry please don't use the `AutoCAD.PlotToPDFDwgzip+prod` we are no more allowing this activity for public consumption,  instead of that please `AutoCAD.PlotToPDF+prod` 

Workitem code : https://github.com/MadhukarMoogala/FDA_PlotToPdf_v3/blob/aec8eac3c8bd5b13ce36fbbe7bf8094aa0d075d4/Client/App.cs#L187

```
var workItem = new WorkItem
            {
                ActivityId = "AutoCAD.PlotToPDF+prod",
                Arguments = new Dictionary<string, IArgument>()
                {
                    { 
                        "HostDwg", new XrefTreeArgument()
                                {
                                 Url ="https://download.autodesk.com/us/samplefiles/acad/blocks_and_tables_-_metric.dwg",
                                 Verb = Verb.Get
                                }
                    },
                    {
                    "Result", new XrefTreeArgument()
                    {
                        
                        Verb = Verb.Put,
Url = string.Format("https://developer.api.autodesk.com/oss/v2/buckets/{0}/objects/{1}",  Owner.ToLower(),outputFileOssName ),
                      Headers = new Dictionary<string, string>()
                      {
                         { "Authorization", "Bearer " + oauth.access_token }
                      }
                    }
                    }
                }
            };
            
```
 I will fix this code and merge later tomorrow

**Comment by maxstefaniv** [comment]
@MadhukarMoogala Thank you very much! it was killing me. Could you please point me in the correct direction if I wanted for example to plot into .png or .jpg instead of .pdf
What documentation should I start looking. I guess it would be something like a custom activity?
Thank you in advance!

**Comment by MadhukarMoogala** [comment]
@maxstefaniv  - I would encourage you to go through our  Design Automation Step by Step tutorial - https://forge.autodesk.com/en/docs/design-automation/v3/tutorials/autocad/about_this_tutorial/
https://learnforge.autodesk.io/#/tutorials/modifymodels

After going through this tutorials, if you have difficulties, please book a slot in calendly 

https://calendly.com/autodeskforge/madhukar-moogala?month=2021-05

>example to plot into .png or .jpg instead of .pdf
What documentation should I start looking. I guess it would be something like a custom activity?

You need a custom activity, you need to have knowledge of AutoCAD API too.

**Comment by maxstefaniv** [comment]
Hello, is there a way to select one of the default CTBs on autocad through "AutoCAD.PlotToPDF+prod" this activity?
https://stackoverflow.com/questions/55704061/please-let-me-know-the-script-for-applying-ctb-when-converting-dwg-file-to-pdf
Here it states that It is possible to upload one but for me, it would be enough for example to select one of the default ones:
![image](https://user-images.githubusercontent.com/62515255/123253629-f3f21b80-d4ed-11eb-894c-5c001ccb008e.png)
For example to go directly to the Greyscale.

**Comment by MadhukarMoogala** [comment]
The `AutoCAD.PlotToPDF+prod` activity uses plotstyle assigned in the drawing, but if you prefer to use `Greyscale` you need to brew your own activity, [check ](https://knowledge.autodesk.com/support/autocad/learn-explore/caas/CloudHelp/cloudhelp/2019/ENU/AutoCAD-Core/files/GUID-625E395D-143A-494F-A1EA-1BF119B927DC-htm.html)

> Plot style table name
> (Available if Plot with plot styles = Yes) Specifies a plot style table name. Enter ? to display a list of available plot styles.

**Comment by maxstefaniv** [comment]
T_T I had so much hopes that I could just add an extra "XrefTreeArgument"...
So I am back to square one, because for my own activity I need Autocad API skills...
Thank-you for your help. Right now is easier to ask .dwg author to set Greyscale before giving me the file.
Is there some kind of course from AutoDesk with in house trainer, so I could get the skills a bit faster than on my own?

**Comment by MadhukarMoogala** [comment]
@maxstefaniv  - We have retired AutoCAD API in-house training workshops sometime back, now the product API is matured, and we have created great community of AutoCAD developer ecosystem, the knowledge is available on forums, stackoverflow.

- [Forums](https://forums.autodesk.com/t5/net/bd-p/152)
- [Swamp](https://www.theswamp.org/index.php?board=27.0)
- [StackOverFlow](https://stackoverflow.com/questions/tagged/autocad-plugin)

**Comment by maxstefaniv** [comment]
@MadhukarMoogala 
Hello! I am excited because I started attacking my issue from autocad api side, and step bys tep I am getting closer to a solution that I am looking for, that is all thanks to you.
I have one more question: is it possible to see source code for yor default `AutoCAD.PlotToPDF+prod` I need to be able to track how it defaults for plotting in case I send a .dwg with personalised CTB or a unique plotter.

Maybe I did not explain myself well, I kind of would like to see the source code as if I wanted to create "myActivity" from scratch but exactly the same as `AutoCAD.PlotToPDF+prod`. 

If that is possible it would skyroket my advances.

Thank you in advance.

**Comment by MadhukarMoogala** [comment]
@maxstefaniv - The `AutoCAD.PlotToPDF+prod`  is a just a script of commands.
`"_tilemode 0 -export _pdf _all result.pdf\n"`

You can view any activity definition by run a GET
```
curl --request GET --url 'https://developer.api.autodesk.com/da/us-east/v3/activities/AutoCAD.PlotToPDF+prod' --header 'Authorization: Bearer blah blah' --header 'Content-Type: application/json'
```


```
{
  "commandLine": [
    "$(engine.path)\\accoreconsole.exe /i \"$(args[HostDwg].path)\" /s $(settings[script].path) /suppressGraphics"
  ],
  "parameters": {
    "HostDwg": {
      "verb": "get",
      "description": "Host drawing to be loaded into acad.",
      "required": true,
      "localName": "$(HostDwg)"
    },
    "Result": {
      "verb": "post",
      "description": "Results",
      "required": true,
      "localName": "result.pdf"
    }
  },
  "id": "AutoCAD.PlotToPDF+prod",
  "engine": "Autodesk.AutoCAD+24_1",
  "appbundles": [],
  "settings": {
    "script": {
      "value": "_tilemode 0 -export _pdf _all result.pdf\n"
    }
  },
  "description": "PlotToPdf for all layouts.",
  "version": 7
}
```

**Comment by maxstefaniv** [comment]
@MadhukarMoogala 
I did not explain myself. Imagine I have a file with a pre set plotting configuration where I specified a unique plotter and a unique Plot Style Table. Such as:
![image](https://user-images.githubusercontent.com/62515255/123621616-b18d4f00-d80b-11eb-811d-bdc658f022b3.png)
When I sent this into FORGE for `AutoCAD.PlotToPDF+prod` it will plot but using another CTB.
I suspect there is somewhere code responsible to select a default CTB configuration and a default Plotter Name. That is the code I would like to examine. I guess it would look kind of like this:
```
public static void LayoutChangePlotSettings()
        {
            // Get the current document and database, and start a transaction
            Document acDoc = Application.DocumentManager.MdiActiveDocument;
            Database acCurDb = acDoc.Database;

            using (Transaction acTrans = acCurDb.TransactionManager.StartTransaction())
            {
                // Reference the Layout Manager
                LayoutManager acLayoutMgr = LayoutManager.Current;

                // Get the current layout and output its name in the Command Line window
                Layout acLayout = acTrans.GetObject(acLayoutMgr.GetLayoutId(acLayoutMgr.CurrentLayout),
                                                    OpenMode.ForRead) as Layout;

                // Output the name of the current layout and its device
                acDoc.Editor.WriteMessage("\nCurrent layout: " + acLayout.LayoutName);

                acDoc.Editor.WriteMessage("\nCurrent device name: " + acLayout.PlotConfigurationName);

                // Get a copy of the PlotSettings from the layout
                PlotSettings acPlSet = new PlotSettings(acLayout.ModelType);
                acPlSet.CopyFrom(acLayout);

                // Update the PlotConfigurationName property of the PlotSettings object
                PlotSettingsValidator acPlSetVdr = PlotSettingsValidator.Current;
                acPlSetVdr.SetPlotConfigurationName(acPlSet, "DWG To PDF.pc3", "ANSI_B_(11.00_x_17.00_Inches)");

                // Zoom to show the whole paper
                acPlSetVdr.SetZoomToPaperOnUpdate(acPlSet, true);

                // Update the layout
                acLayout.UpgradeOpen();
                acLayout.CopyFrom(acPlSet);

                // Output the name of the new device assigned to the layout
                acDoc.Editor.WriteMessage("\nNew device name: " + acLayout.PlotConfigurationName);

                // Save the new objects to the database
                acTrans.Commit();
            }

            // Update the display
            acDoc.Editor.Regen();
        }
```

**Comment by MadhukarMoogala** [comment]
Let me explain in detail 

Note CTB and PlotStyle means same.

1.  `AutoCAD.PlotToPDF+prod` plots a drawing to PDF with default plotstyle if the plotstyle assigned drawing is not found.
2.  If you want `AutoCAD.PlotToPDF+prod`  to plot a drawing to PDF with plotstyle assigned in the drawing, then you need to send custom CTB file along with the drawing in your workItem.

Example: 
Note: `"localName": "FDA.ctb"` , the localName should be the name of the ctb assigned to the drawing.
```
{
	"activityId": "AutoCAD.PlotToPDF+prod",
	"arguments": {
		"HostDwg": {
			"url": "https://developer.api.autodesk.com/oss/v2/signedresources/7c22dc55-54b3-4be4-944b-4fd9c14065b8?region=US",
			"headers": null,
			"references": [
				{
					"localName": "FDA.ctb",
					"references": null,
					"verb": "get",
					"url": "https://developer.api.autodesk.com/oss/v2/signedresources/7f1d4ecb-0b80-43f5-8b46-92d175d09ced?region=US"
				}
			],
			"verb": "get"
		},
		"Result": {
			"headers": null,
			"url": "https://developer.api.autodesk.com/oss/v2/signedresources/e53bfb56-72a5-4f5e-bd5f-f3dfc3a04527?region=US",
			"verb": "put"
		}
	}
}
```
3. If you want to `AutoCAD.PlotToPDF+prod` to plot a drawing to a pdf with neither assigned plotstyle nor default plotstyle but with choice of your plotstyle that is native (available) in AutoCAD, it is not possible with the said activity, you need to create your custom activity, 

 - Create a .NET command lets say "SetPlotStyle" that takes an input  for example `Greyscale.ctb` to set to current style sheet.
 Refer - [SetCurrentStyleSheet ](https://help.autodesk.com/view/OARX/2022/ENU/?guid=OARX-ManagedRefGuide-Autodesk_AutoCAD_DatabaseServices_PlotSettingsValidator_SetCurrentStyleSheet_PlotSettings_string)API [example code. ](https://stackoverflow.com/questions/62760622/changing-printer-support-file-path-in-forge-design-automation-api)
- Create Activity

```
{
	"commandLine": [
		"$(engine.path)\\accoreconsole.exe /i \"$(args[HostDwg].path)\" /s $(settings[script].path) /suppressGraphics"
	],
	"parameters": {
		"HostDwg": {
			"verb": "get",
			"description": "Host drawing to be loaded into acad.",
			"required": true,
			"localName": "$(HostDwg)"
		},
		"Result": {
			"verb": "post",
			"description": "Results",
			"required": true,
			"localName": "result.pdf"
		}
	},
	"id": "PlotToPDFCTB",
	"engine": "Autodesk.AutoCAD+24_1",
	"appbundles": [],
	"settings": {
		"script": {
			"value": "SetPlotStyle\n\"Greyscale.ctb\"\n_tilemode 0 -export _pdf _all result.pdf\n"
		}
	},
	"description": "PlotToPdf for all layouts with greyscale plotstyle"	
}
```
- Create WorkItem

```
{
	"activityId": "{{ _.nickName }}.PlotToPDFCTB+{{ _.alias }}",
	"arguments": {
		"HostDwg": {
			"url": "https://developer.api.autodesk.com/oss/v2/signedresources/7c22dc55-54b3-4be4-944b-4fd9c14065b8?region=US",
			"headers": null,
			"verb": "get"
		},
		"Result": {
			"headers": null,
			"url": "https://developer.api.autodesk.com/oss/v2/signedresources/e53bfb56-72a5-4f5e-bd5f-f3dfc3a04527?region=US",
			"verb": "put"
		}
	}
}
```

**Comment by maxstefaniv** [comment]
@MadhukarMoogala Thank you very very much!! Managed to do most of what I require. 
One more question.
Imagine I have a `sample.dwg` with default CTB files. I want to use forge as:
- send to forge `sample.dwg` + external `Unique.ctb` as a URL link that allows to download or as an additional file in a zip.
- then in forge place the `Unique.ctb` in the corresponding place/folder so I can automate in forge this command:
   - `acPlSetVdr.SetCurrentStyleSheet(acPlSet, "Unique.ctb");`
- Finally plot to pdf.

Basically instead of having the "Unique.ctb" assigned as a plotting config in a local machine I want to do it in Forge. This would allow me as a user to not have installed Autocad but I will be able to send a .dwg file + .ctb file into forge and the process will be automated.
If my explanation is unclear, please let me know.

What I already tried is to do a: `byte[] response = new System.Net.WebClient().DownloadData("link with .ctb");` 
but that gets me an error "Unable to connect to the remote server".
I wanted to get the ctb file from my cloud storage and as I already explained apply that CTB to an uploaded dwg.
I guess I also need to know if I have wrote permissions for the folders where the CTB are stored in Forge client.

Please comment for possible solutions.
Thank you in advance for your help.

**Comment by MadhukarMoogala** [comment]
@maxstefaniv  - I sent an email about our plans in private to you.
Possible solution for you is to ship the associated CTB url along with drawing in the workitem, forge will do a `GET` request on the URL, and apply the ctb to the drawing.

**Comment by maxstefaniv** [comment]
@MadhukarMoogala 
That is one of the possible approaches or I could also upload it in a zip to forge. the only question is after I have the file on Forge. Where I can Store it? because in order to detect new .ctb files in local they need to be in ".....Autodesk\AutoCAD 2021\R24.0\enu\Plotters\Plot Styles"
Bun on forge Cloud what would be the route where I need to place the file?

**Comment by MadhukarMoogala** [comment]
@maxstefaniv , you can copy the files from the bundle to Plotter folders., I have answered this in [detail here.](https://stackoverflow.com/questions/62760622/changing-printer-support-file-path-in-forge-design-automation-api/62773224#62773224)
